<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc2df4f1dc6c50af8e3b986d8d8abdb12
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc2df4f1dc6c50af8e3b986d8d8abdb12::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc2df4f1dc6c50af8e3b986d8d8abdb12::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
